---
title: "Data Cleaning"
date: "2024-10-21"
output: pdf_document
---

```{r setup, include=FALSE}
library(readxl)
library(knitr)  
library(kableExtra)
library(tidyverse)
library(stringr)
library(tidyverse)
```

# Data Cleaning

```{r}
# Load Data
rituals <- read_excel("Copy of Coded data from postcombat rituals July 18.xlsx")
glimpse(rituals)
```

```{r}
# delete the second column (duplicated)
rituals <- subset(rituals, select = -`What is the name of the culture...2`)
rituals<- subset(rituals, select = -...34)
rituals<- subset(rituals, select = -...40)
rituals<- subset(rituals, select = -...41)
rituals<- subset(rituals, select = -...42)
rituals<- subset(rituals, select = -...43)
rituals<- subset(rituals, select = -...44)
rituals <- rituals %>% slice(-73:-97)

# change the cloumn name of What is the name of the culture
colnames(rituals)[colnames(rituals) == "What is the name of the culture...4"] <- "Culture"
colnames(rituals)[colnames(rituals) == "What is the culture's region"] <- "Region"
colnames(rituals)[colnames(rituals) == "Does the text about the ritual describe Periods of Separation (Isolation) and Reintegration?"] <- "Isolation_Reintegration"
colnames(rituals)[colnames(rituals) == "Does the the text about the ritual describe Forgiveness and Acceptance by the community?"] <- "Forgiveness"
colnames(rituals)[colnames(rituals) == "Does the Ritual appear to involve a Purification/Cleansing of the participant?"] <- "Purification_or_Cleansing"
colnames(rituals)[colnames(rituals) == "Based on your reading of the text, would you consider the ritual therapeutic?"] <- "Therapeutic"
colnames(rituals)[colnames(rituals) == "Is the Ritual described as “healing” or “transformative”"] <- "Healing"

# Change Unsure into No
rituals[, 9:37] <- apply(rituals[, 9:37], 2, function(x) ifelse(x == "Unsure", "No", x))
```

```{r}
# write into csv
write.csv(rituals, file = "rituals.csv", row.names = FALSE)
```

